name: LLFRankUp
author: L337Lobster
website: http://dev.bukkit.org/bukkit-plugins/llfrankup/
main: com.llfrealms.LLFRankUp.LLFRankUp
depend: [CreateYourOwnMenus]
version: 1.6

commands:
    /rankup:
       description: Open the next rank up menu.
       aliases: /ru
       usage: /<command>