name: LLFRankUp
author: L337Lobster
website: http://llfrealms.com
main: com.llfrealms.LLFRankUp.LLFRankUp
depend: [CreateYourOwnMenus]
version: 2.5

commands:
    /rankup:
       description: Open the next rank up menu.
       aliases: /ru
       permission-message: You do not have permission for this command
       usage: /<command>